### ISSUE TITLE
Error "variable $files overwritten in foreach" in latte on version 2.4

### ISSUE THREAD

**Issue by Myiyk** [janmarek/WebLoader#129]
webloader 2.5.0
latte/latte 2.4.0

> Error: WebLoader\Nette\Diagnostics\Panel
> ErrorException: Variable $files overwritten in foreach on line 11 in /Library/WebServer/Documents/a8/a8reklama.cz/vendor/latte/latte/src/Latte/Engine.php(162) : eval()'d code:81
> Stack trace:
> #0 [internal function]: Tracy\Bar->Tracy\{closure}(1024, 'Variable $files...', '/Library/WebSer...', 81, Array)
> #1 /Library/WebServer/Documents/a8/a8reklama.cz/vendor/latte/latte/src/Latte/Engine.php(162) : eval()'d code(81): trigger_error('Variable $files...')
> #2 /Library/WebServer/Documents/a8/a8reklama.cz/vendor/latte/latte/src/Latte/Runtime/Template.php(156): Template5519eab23f->prepare()
> #3 /Library/WebServer/Documents/a8/a8reklama.cz/vendor/latte/latte/src/Latte/Runtime/Template.php(323): Latte\Runtime\Template->render()
> #4 /Library/WebServer/Documents/a8/a8reklama.cz/vendor/latte/latte/src/Latte/Engine.php(82): Latte\Runtime\Template->capture(Array)
> #5 /Library/WebServer/Documents/a8/a8reklama.cz/vendor/janmarek/webloader/WebLoader/Nette/Diagnostics/Panel.php(136): Latte\Engine->renderToString('/Library/WebSer...', Array)
> #6 /Library/WebServer/Documents/a8/a8reklama.cz/vendor/janmarek/webloader/WebLoader/Nette/Diagnostics/Panel.php(146): WebLoader\Nette\Diagnostics\Panel->getTable()
> #7 /Library/WebServer/Documents/a8/a8reklama.cz/vendor/tracy/tracy/src/Tracy/Bar.php(135): WebLoader\Nette\Diagnostics\Panel->getPanel()
> #8 /Library/WebServer/Documents/a8/a8reklama.cz/vendor/tracy/tracy/src/Tracy/Bar.php(81): Tracy\Bar->renderPanels()
> #9 /Library/WebServer/Documents/a8/a8reklama.cz/vendor/tracy/tracy/src/Tracy/Debugger.php(251): Tracy\Bar->render()
> #10 [internal function]: Tracy\Debugger::shutdownHandler()
> #11 {main}

**Comment by vymak** [comment]
#130

**Comment by lukasojd** [comment]
+1

**Comment by lukasojd** [comment]
+1 again

**Comment by revoke** [comment]
Just only change name of variable $files on the lines 11 and 21 in file vendor/janmarek/webloader/Webloader/Nette/Diagnostics/panel.latte

**Comment by lukasojd** [comment]
@revoke Did you sent PR?

**Comment by lukasojd** [comment]
https://github.com/janmarek/WebLoader/issues/116

**Comment by JohnyRicio** [comment]
Please release it. In 2.5 version I have still this isue.
